# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20170530_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.FileField(default=False, upload_to='staff'),
        ),
    ]
