# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20170531_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='staff'),
        ),
    ]
