# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20170531_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='staff'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
